const countries = [
  // key, value, code, iso2, currency, currencyCode, apiUrl, gothumb_url, login_url, default_timezone
  ["Albania", "Albania", "355", "AL", "Lek", "ALL"],
  ["Algeria", "Algeria", "213", "DZ", "Algerian Dinar", "DZD"],
  ["American Samoa", "American Samoa", "1 684", "AS", "US Dollar", "USD"],
  ["Andorra", "Andorra", "376", "AD", "Euro", "EUR"],
  ["Angola", "Angola", "244", "AO", "Kwanza", "AOA"],
  ["Anguilla", "Anguilla", "1 264", "AI", "East Caribbean Dollar", "XCD"],
  ["Argentina", "Argentina", "54", "AR", "Argentine Peso", "ARS"],
  ["Armenia", "Armenia", "374", "AM", "Armenian Dram", "AMD"],
  ["Aruba", "Aruba", "297", "AW", "Aruban Florin", "AWG"],
  [
    "Australia",
    "Australia",
    "61",
    "AU",
    "Australian Dollar",
    "AUD",
    "https://api.au.healthbeats.co/v1",
    "https://gothumb.au.healthbeats.co",
    "https://login.au.healthbeats.co",
    "Australia/Sydney",
  ],
  ["Austria", "Austria", "43", "AT", "Euro", "EUR"],
  ["Azerbaijan", "Azerbaijan", "994", "AZ", "Azerbaijanian Manat", "AZN"],
  ["Bahamas", "Bahamas", "1 242", "BS", "Bahamian Dollar", "BSD"],
  ["Bahrain", "Bahrain", "973", "BH", "Bahraini Dinar", "BHD"],
  ["Bangladesh", "Bangladesh", "880", "BD", "Taka", "BDT"],
  ["Barbados", "Barbados", "1 246", "BB", "Barbados Dollar", "BBD"],
  ["Belarus", "Belarus", "375", "BY", "Belarusian Ruble", "BYN"],
  ["Belgium", "Belgium", "32", "BE", "Euro", "EUR"],
  ["Belize", "Belize", "501", "BZ", "Belize Dollar", "BZD"],
  ["Benin", "Benin", "229", "BJ", "CFA Franc BCEAO", "XOF"],
  ["Bermuda", "Bermuda", "1 441", "BM", "Bermudian Dollar", "BMD"],
  ["Bhutan", "Bhutan", "975", "BT", "Indian Rupee", "INR"],
  ["Botswana", "Botswana", "267", "BW", "Pula", "BWP"],
  ["Bouvet Island", "Bouvet Island", "47", "BV", "Norwegian Krone", "NOK"],
  ["Brazil", "Brazil", "55", "BR", "Brazilian Real", "BRL"],
  [
    "British Indian Ocean Territory",
    "British Indian Ocean Territory",
    "246",
    "IO",
    "US Dollar",
    "USD",
  ],
  ["Bulgaria", "Bulgaria", "359", "BG", "Bulgarian Lev", "BGN"],
  ["Burkina Faso", "Burkina Faso", "226", "BF", "CFA Franc BCEAO", "XOF"],
  ["Burundi", "Burundi", "257", "BI", "Burundi Franc", "BIF"],
  ["Cambodia", "Cambodia", "855", "KH", "Riel", "KHR"],
  ["Cameroon", "Cameroon", "237", "CM", "CFA Franc BEAC", "XAF"],
  ["Canada", "Canada", "1", "CA", "Canadian Dollar", "CAD"],
  ["Cape Verde", "Cape Verde", "238", "CV", "Cape Verdean escudo", "CVE"],
  [
    "Central African Republic",
    "Central African Republic",
    "236",
    "CF",
    "CFA Franc BEAC",
    "XAF",
  ],
  ["Chad", "Chad", "235", "TD", "CFA Franc BEAC", "XAF"],
  ["Chile", "Chile", "56", "CL", "Chilean Peso", "CLP"],
  ["China", "China", "86", "CN", "Renminbi", "CNY"],
  ["Colombia", "Colombia", "57", "CO", "Colombian Peso", "COP"],
  ["Comoros", "Comoros", "269", "KM", "Comoro Franc", "KMF"],
  ["Costa Rica", "Costa Rica", "506", "CR", "Costa Rican Colon", "CRC"],
  ["Croatia", "Croatia", "385", "HR", "Croatian Kuna", "HKR"],
  ["Cuba", "Cuba", "53", "CU", "Cuban Peso", "CUP"],
  ["Cyprus", "Cyprus", "357", "CY", "Euro", "EUR"],
  ["Denmark", "Denmark", "45", "DK", "Danish Krone", "DKK"],
  ["Djibouti", "Djibouti", "253", "DJ", "Djibouti Franc", "DJF"],
  ["Ecuador", "Ecuador", "593", "EC", "US Dollar", "USD"],
  ["Egypt", "Egypt", "20", "EG", "Egyptian Pound", "EGP"],
  ["El Salvador", "El Salvador", "503", "SV", "US Dollar", "USD"],
  [
    "Equatorial Guinea",
    "Equatorial Guinea",
    "240",
    "GQ",
    "CFA Franc BEAC",
    "XAF",
  ],
  ["Eritrea", "Eritrea", "291", "ER", "Nakfa", "ERN"],
  ["Estonia", "Estonia", "372", "EE", "Euro", "EUR"],
  ["Ethiopia", "Ethiopia", "251", "ET", "Ethiopian Birr", "ETB"],
  ["Fiji", "Fiji", "679", "FJ", "Fiji Dollar", "FJD"],
  ["Finland", "Finland", "358", "FI", "Euro", "EUR"],
  ["France", "France", "33", "FR", "Euro", "EUR"],
  ["Gabon", "Gabon", "44", "GA", "CFA Franc BEAC", "XAF"],
  ["Gambia", "Gambia", "220", "GM", "Dalasi", "GMD"],
  ["Germany", "Germany", "49", "DE", "Euro", "EUR"],
  ["Ghana", "Ghana", "233", "GH", "Ghana Cedi", "GHS"],
  ["Gibraltar", "Gibraltar", "350", "GI", "Gibraltar Pound", "GIP"],
  ["Greece", "Greece", "30", "GR", "Euro", "EUR"],
  ["Greenland", "Greenland", "299", "GL", "Danish Krone", "DKK"],
  ["Grenada", "Grenada", "995", "GD", "East Caribbean Dollar", "XCD"],
  ["Guadeloupe", "Guadeloupe", "590", "GP", "Euro", "EUR"],
  ["Guam", "Guam", "1 671", "GU", "US Dollar", "USD"],
  ["Guatemala", "Guatemala", "502", "GT", "Quetzal", "GTQ"],
  ["Guernsey", "Guernsey", "44", "GG", "Pound Sterling", "GBP"],
  ["Guinea", "Guinea", "224", "GN", "Guinea Franc", "GNF"],
  ["Guyana", "Guyana", "592", "GY", "Guyana Dollar", "GYD"],
  ["Haiti", "Haiti", "509", "HT", "Gourde", "HTG"],
  ["Honduras", "Honduras", "504", "HN", "Lempira", "HNL"],
  ["Hungary", "Hungary", "36", "HU", "Forint", "HUF"],
  ["Iceland", "Iceland", "354", "IS", "Iceland Krona", "ISK"],
  ["India", "India", "91", "IN", "Indian Rupee", "INR"],
  ["Indonesia", "Indonesia", "62", "ID", "Rupiah", "IDR"],
  ["Iraq", "Iraq", "964", "IQ", "Iraqi Dinar", "IQD"],
  ["Ireland", "Ireland", "353", "IE", "Euro", "EUR"],
  ["Italy", "Italy", "39", "IT", "Euro", "EUR"],
  ["Jamaica", "Jamaica", "1 876", "JM", "Jamaican Dollar", "JMD"],
  ["Japan", "Japan", "81", "JP", "Yen", "JPY"],
  ["Jersey", "Jersey", "44", "JE", "Pound Sterling", "GBP"],
  ["Jordan", "Jordan", "962", "JO", "Jordanian Dinar", "JOD"],
  ["Kazakhstan", "Kazakhstan", "7", "KZ", "Kazakhstani Tenge", "KZT"],
  ["Kenya", "Kenya", "254", "KE", "Kenyan Shilling", "KES"],
  ["Kiribati", "Kiribati", "686", "KI", "Australian Dollar", "AUD"],
  ["Kuwait", "Kuwait", "965", "KW", "Kuwaiti Dinar", "KWD"],
  ["Lebanon", "Lebanon", "961", "LB", "Lebanese Pound", "LBP"],
  ["Liberia", "Liberia", "231", "LR", "Liberian Dollar", "LRD"],
  ["Libya", "Libya", "218", "LY", "Libyan Dinar", "LYD"],
  ["Liechtenstein", "Liechtenstein", "423", "LI", "Swiss Franc", "CHF"],
  ["Luxembourg", "Luxembourg", "352", "LU", "Euro", "EUR"],
  ["Malaysia", "Malaysia", "60", "MY", "Malaysian Ringgit", "MYR"],
  ["Mauritania", "Mauritania", "222", "MR", "Ouguiya", "MRO"],
  ["Mauritius", "Mauritius", "230", "MU", "Mauritius Rupee", "MUR"],
  ["Mexico", "Mexico", "52", "MX", "Mexican Peso", "MXN"],
  ["Morocco", "Morocco", "212", "MA", "Moroccan Dirham", "MAD"],
  ["Namibia", "Namibia", "264", "NA", "Namibia Dollar", "NAD"],
  ["Nauru", "Nauru", "674", "NR", "Australian Dollar", "AUD"],
  ["Nepal", "Nepal", "977", "NP", "Nepalese Rupee", "NPR"],
  ["Netherlands", "Netherlands", "31", "NL", "Euro", "EUR"],
  ["New Caledonia", "New Caledonia", "687", "NC", "CFP Franc", "XPF"],
  ["New Zealand", "New Zealand", "64", "NZ", "New Zealand Dollar", "NZD"],
  ["Nigeria", "Nigeria", "234", "NG", "Naira", "NGN"],
  ["Niue", "Niue", "683", "NU", "New Zealand Dollar", "NZD"],
  ["Norway", "Norway", "47", "NO", "Norwegian Krone", "NOK"],
  ["Pakistan", "Pakistan", "92", "PK", "Pakistan Rupee", "PKR"],
  ["Palau", "Palau", "680", "PW", "US Dollar", "USD"],
  ["Paraguay", "Paraguay", "595", "PY", "Paraguayan Guarani", "PYG"],
  ["Peru", "Peru", "51", "PE", "Sol", "SOL"],
  [
    "Philippines",
    "Philippines",
    "63",
    "PH",
    "Philippine Peso",
    "PHP",
    "https://api.sg.healthbeats.co/v1",
    "https://gothumb.sg.healthbeats.co",
    "https://login.sg.healthbeats.co",
    "Asia/Manila",
  ],
  ["Poland", "Poland", "48", "PL", "Polish Zloty", "PLN"],
  ["Portugal", "Portugal", "351", "PT", "Euro", "EUR"],
  ["Puerto Rico", "Puerto Rico", "1 787", "PR", "US Dollar", "USD"],
  ["Qatar", "Qatar", "974", "QA", "Qatari Rial", "QAR"],
  ["Romania", "Romania", "40", "RO", "Romanian Leu", "RON"],
  ["Rwanda", "Rwanda", "250", "RW", "Rwanda Franc", "RWF"],
  ["Samoa", "Samoa", "685", "WS", "Tala", "WST"],
  ["San Marino", "San Marino", "378", "SM", "Euro", "EUR"],
  ["Saudi Arabia", "Saudi Arabia", "966", "SA", "Saudi Riyal", "SAR"],
  ["Senegal", "Senegal", "221", "SN", "CFA Franc BCEAO", "XOF"],
  ["Serbia", "Serbia", "381", "RS", "Serbian Dinar", "RSD"],
  ["Seychelles", "Seychelles", "248", "SC", "Seychelles Rupee", "SCR"],
  ["Sierra Leone", "Sierra Leone", "232", "SL", "Leone", "SLL"],
  [
    "Singapore",
    "Singapore",
    "65",
    "SG",
    "Singapore Dollar",
    "SGD",
    "https://api.sg.healthbeats.co/v1",
    "https://gothumb.sg.healthbeats.co",
    "https://login.sg.healthbeats.co",
    "Asia/Singapore",
  ],
  [
    "Sint Maarten",
    "Sint Maarten",
    "1 721",
    "SX",
    "Netherlands Antillean Guilder",
    "ANG",
  ],
  ["Slovakia", "Slovakia", "421", "SK", "Euro", "EUR"],
  ["Slovenia", "Slovenia", "386", "SI", "Euro", "EUR"],
  ["Somalia", "Somalia", "252", "SO", "Somali Shilling", "SOS"],
  ["South Africa", "South Africa", "27", "ZA", "South African Rand", "ZAR"],
  ["Spain", "Spain", "34", "ES", "Euro", "EUR"],
  ["Sri Lanka", "Sri Lanka", "94", "LK", "Sri Lanka Rupee", "LKR"],
  ["Suriname", "Suriname", "597", "SR", "Surinam Dollar", "SRD"],
  ["Swaziland", "Swaziland", "268", "SZ", "Lilangeni", "SZL"],
  ["Sweden", "Sweden", "46", "SE", "Swedish Krona", "SEK"],
  ["Switzerland", "Switzerland", "41", "CH", "Swiss Franc", "CHF"],
  [
    "Thailand",
    "Thailand",
    "66",
    "TH",
    "Thai Baht",
    "THB",
    "https://api.sg.healthbeats.co/v1",
    "https://gothumb.sg.healthbeats.co",
    "https://login.sg.healthbeats.co",
    "Asia/Bangkok",
  ],
  ["Togo", "Togo", "228", "TG", "CFA Franc BCEAO", "XOF"],
  ["Tokelau", "Tokelau", "690", "TK", "New Zealand Dollar", "NZD"],
  ["Tunisia", "Tunisia", "216", "TN", "Tunisian Dinar", "TND"],
  ["Turkey", "Turkey", "90", "TR", "Turkish Lira", "TRY"],
  ["Tuvalu", "Tuvalu", "688", "TV", "Australian Dollar", "AUD"],
  ["Ukraine", "Ukraine", "380", "UA", "Ukrainian Hryvnia", "UAH"],
  [
    "United Arab Emirates",
    "United Arab Emirates",
    "971",
    "AE",
    "UAE Dirham",
    "AED",
  ],
  ["United Kingdom", "United Kingdom", "44", "UK", "Pound Sterling", "GBP"],
  [
    "United States",
    "United States",
    "1",
    "US",
    "US Dollar",
    "USD",
    "https://api.us.healthbeats.co/v1",
    "https://gothumb.us.healthbeats.co",
    "https://login.us.healthbeats.co",
    "America/New_York",
  ],
  ["Uzbekistan", "Uzbekistan", "998", "UZ", "Uzbekistan Sum", "UZS"],
  ["Vanuatu", "Vanuatu", "678", "VU", "Vatu", "VUV"],
  ["Yemen", "Yemen", "967", "YE", "Yemeni Rial", "YER"],
  ["Zambia", "Zambia", "260", "ZM", "Zambian Kwacha", "ZMW"],
  ["Zimbabwe", "Zimbabwe", "263", "ZW", "Zimbabwe Dollar", "ZWL"],
];

const timezonedb = [
  ["AF", "Afghanistan", "Asia/Kabul", "UTC +04:30"],
  ["AL", "Albania", "Europe/Tirane", "UTC +02:00"],
  ["DZ", "Algeria", "Africa/Algiers", "UTC +01:00"],
  ["AS", "American Samoa", "Pacific/Pago_Pago", "UTC -11:00"],
  ["AD", "Andorra", "Europe/Andorra", "UTC +02:00"],
  ["AO", "Angola", "Africa/Luanda", "UTC +01:00"],
  ["AI", "Anguilla", "America/Anguilla", "UTC -04:00"],
  ["AQ", "Antarctica", "Antarctica/Casey", "UTC +08:00"],
  ["AQ", "Antarctica", "Antarctica/Davis", "UTC +07:00"],
  ["AQ", "Antarctica", "Antarctica/DumontDUrville", "UTC +10:00"],
  ["AQ", "Antarctica", "Antarctica/Mawson", "UTC +05:00"],
  ["AQ", "Antarctica", "Antarctica/McMurdo", "UTC +12:00"],
  ["AQ", "Antarctica", "Antarctica/Palmer", "UTC -03:00"],
  ["AQ", "Antarctica", "Antarctica/Rothera", "UTC -03:00"],
  ["AQ", "Antarctica", "Antarctica/Syowa", "UTC +03:00"],
  ["AQ", "Antarctica", "Antarctica/Troll", "UTC +02:00"],
  ["AQ", "Antarctica", "Antarctica/Vostok", "UTC +06:00"],
  ["AG", "Antigua and Barbuda", "America/Antigua", "UTC -04:00"],
  ["AR", "Argentina", "America/Argentina/Buenos_Aires", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Catamarca", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Cordoba", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Jujuy", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/La_Rioja", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Mendoza", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Rio_Gallegos", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Salta", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/San_Juan", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/San_Luis", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Tucuman", "UTC -03:00"],
  ["AR", "Argentina", "America/Argentina/Ushuaia", "UTC -03:00"],
  ["AM", "Armenia", "Asia/Yerevan", "UTC +04:00"],
  ["AW", "Aruba", "America/Aruba", "UTC -04:00"],
  ["AU", "Australia", "Antarctica/Macquarie", "UTC +11:00"],
  ["AU", "Australia", "Australia/Adelaide", "UTC +09:30"],
  ["AU", "Australia", "Australia/Brisbane", "UTC +10:00"],
  ["AU", "Australia", "Australia/Broken_Hill", "UTC +09:30"],
  ["AU", "Australia", "Australia/Currie", "UTC +10:00"],
  ["AU", "Australia", "Australia/Darwin", "UTC +09:30"],
  ["AU", "Australia", "Australia/Eucla", "UTC +08:45"],
  ["AU", "Australia", "Australia/Hobart", "UTC +10:00"],
  ["AU", "Australia", "Australia/Lindeman", "UTC +10:00"],
  ["AU", "Australia", "Australia/Lord_Howe", "UTC +10:30"],
  ["AU", "Australia", "Australia/Melbourne", "UTC +10:00"],
  ["AU", "Australia", "Australia/Perth", "UTC +08:00"],
  ["AU", "Australia", "Australia/Sydney", "UTC +10:00"],
  ["AT", "Austria", "Europe/Vienna", "UTC +02:00"],
  ["AZ", "Azerbaijan", "Asia/Baku", "UTC +04:00"],
  ["BS", "Bahamas", "America/Nassau", "UTC -04:00"],
  ["BH", "Bahrain", "Asia/Bahrain", "UTC +03:00"],
  ["BD", "Bangladesh", "Asia/Dhaka", "UTC +06:00"],
  ["BB", "Barbados", "America/Barbados", "UTC -04:00"],
  ["BY", "Belarus", "Europe/Minsk", "UTC +03:00"],
  ["BE", "Belgium", "Europe/Brussels", "UTC +02:00"],
  ["BZ", "Belize", "America/Belize", "UTC -06:00"],
  ["BJ", "Benin", "Africa/Porto-Novo", "UTC +01:00"],
  ["BM", "Bermuda", "Atlantic/Bermuda", "UTC -03:00"],
  ["BT", "Bhutan", "Asia/Thimphu", "UTC +06:00"],
  ["BO", "Bolivia, Plurinational State of", "America/La_Paz", "UTC -04:00"],
  [
    "BQ",
    "Bonaire, Sint Eustatius and Saba",
    "America/Kralendijk",
    "UTC -04:00",
  ],
  ["BA", "Bosnia and Herzegovina", "Europe/Sarajevo", "UTC +02:00"],
  ["BW", "Botswana", "Africa/Gaborone", "UTC +02:00"],
  ["BR", "Brazil", "America/Araguaina", "UTC -03:00"],
  ["BR", "Brazil", "America/Bahia", "UTC -03:00"],
  ["BR", "Brazil", "America/Belem", "UTC -03:00"],
  ["BR", "Brazil", "America/Boa_Vista", "UTC -04:00"],
  ["BR", "Brazil", "America/Campo_Grande", "UTC -04:00"],
  ["BR", "Brazil", "America/Cuiaba", "UTC -04:00"],
  ["BR", "Brazil", "America/Eirunepe", "UTC -05:00"],
  ["BR", "Brazil", "America/Fortaleza", "UTC -03:00"],
  ["BR", "Brazil", "America/Maceio", "UTC -03:00"],
  ["BR", "Brazil", "America/Manaus", "UTC -04:00"],
  ["BR", "Brazil", "America/Noronha", "UTC -02:00"],
  ["BR", "Brazil", "America/Porto_Velho", "UTC -04:00"],
  ["BR", "Brazil", "America/Recife", "UTC -03:00"],
  ["BR", "Brazil", "America/Rio_Branco", "UTC -05:00"],
  ["BR", "Brazil", "America/Santarem", "UTC -03:00"],
  ["BR", "Brazil", "America/Sao_Paulo", "UTC -03:00"],
  ["IO", "British Indian Ocean Territory", "Indian/Chagos", "UTC +06:00"],
  ["BN", "Brunei Darussalam", "Asia/Brunei", "UTC +08:00"],
  ["BG", "Bulgaria", "Europe/Sofia", "UTC +03:00"],
  ["BF", "Burkina Faso", "Africa/Ouagadougou", "UTC"],
  ["BI", "Burundi", "Africa/Bujumbura", "UTC +02:00"],
  ["KH", "Cambodia", "Asia/Phnom_Penh", "UTC +07:00"],
  ["CM", "Cameroon", "Africa/Douala", "UTC +01:00"],
  ["CA", "Canada", "America/Atikokan", "UTC -05:00"],
  ["CA", "Canada", "America/Blanc-Sablon", "UTC -04:00"],
  ["CA", "Canada", "America/Cambridge_Bay", "UTC -06:00"],
  ["CA", "Canada", "America/Creston", "UTC -07:00"],
  ["CA", "Canada", "America/Dawson", "UTC -07:00"],
  ["CA", "Canada", "America/Dawson_Creek", "UTC -07:00"],
  ["CA", "Canada", "America/Edmonton", "UTC -06:00"],
  ["CA", "Canada", "America/Fort_Nelson", "UTC -07:00"],
  ["CA", "Canada", "America/Glace_Bay", "UTC -03:00"],
  ["CA", "Canada", "America/Goose_Bay", "UTC -03:00"],
  ["CA", "Canada", "America/Halifax", "UTC -03:00"],
  ["CA", "Canada", "America/Inuvik", "UTC -06:00"],
  ["CA", "Canada", "America/Iqaluit", "UTC -04:00"],
  ["CA", "Canada", "America/Moncton", "UTC -03:00"],
  ["CA", "Canada", "America/Nipigon", "UTC -04:00"],
  ["CA", "Canada", "America/Pangnirtung", "UTC -04:00"],
  ["CA", "Canada", "America/Rainy_River", "UTC -05:00"],
  ["CA", "Canada", "America/Rankin_Inlet", "UTC -05:00"],
  ["CA", "Canada", "America/Regina", "UTC -06:00"],
  ["CA", "Canada", "America/Resolute", "UTC -05:00"],
  ["CA", "Canada", "America/St_Johns", "UTC -02:30"],
  ["CA", "Canada", "America/Swift_Current", "UTC -06:00"],
  ["CA", "Canada", "America/Thunder_Bay", "UTC -04:00"],
  ["CA", "Canada", "America/Toronto", "UTC -04:00"],
  ["CA", "Canada", "America/Vancouver", "UTC -07:00"],
  ["CA", "Canada", "America/Whitehorse", "UTC -07:00"],
  ["CA", "Canada", "America/Winnipeg", "UTC -05:00"],
  ["CA", "Canada", "America/Yellowknife", "UTC -06:00"],
  ["CV", "Cape Verde", "Atlantic/Cape_Verde", "UTC -01:00"],
  ["KY", "Cayman Islands", "America/Cayman", "UTC -05:00"],
  ["CF", "Central African Republic", "Africa/Bangui", "UTC +01:00"],
  ["TD", "Chad", "Africa/Ndjamena", "UTC +01:00"],
  ["CL", "Chile", "America/Punta_Arenas", "UTC -03:00"],
  ["CL", "Chile", "America/Santiago", "UTC -04:00"],
  ["CL", "Chile", "Pacific/Easter", "UTC -06:00"],
  ["CN", "China", "Asia/Shanghai", "UTC +08:00"],
  ["CN", "China", "Asia/Urumqi", "UTC +06:00"],
  ["CX", "Christmas Island", "Indian/Christmas", "UTC +07:00"],
  ["CC", "Cocos (Keeling) Islands", "Indian/Cocos", "UTC +06:30"],
  ["CO", "Colombia", "America/Bogota", "UTC -05:00"],
  ["KM", "Comoros", "Indian/Comoro", "UTC +03:00"],
  ["CG", "Congo", "Africa/Brazzaville", "UTC +01:00"],
  [
    "CD",
    "Congo, the Democratic Republic of the",
    "Africa/Kinshasa",
    "UTC +01:00",
  ],
  [
    "CD",
    "Congo, the Democratic Republic of the",
    "Africa/Lubumbashi",
    "UTC +02:00",
  ],
  ["CK", "Cook Islands", "Pacific/Rarotonga", "UTC -10:00"],
  ["CR", "Costa Rica", "America/Costa_Rica", "UTC -06:00"],
  ["HR", "Croatia", "Europe/Zagreb", "UTC +02:00"],
  ["CU", "Cuba", "America/Havana", "UTC -04:00"],
  ["CW", "Curaçao", "America/Curacao", "UTC -04:00"],
  ["CY", "Cyprus", "Asia/Famagusta", "UTC +03:00"],
  ["CY", "Cyprus", "Asia/Nicosia", "UTC +03:00"],
  ["CZ", "Czech Republic", "Europe/Prague", "UTC +02:00"],
  ["CI", "Côte d'Ivoire", "Africa/Abidjan", "UTC"],
  ["DK", "Denmark", "Europe/Copenhagen", "UTC +02:00"],
  ["DJ", "Djibouti", "Africa/Djibouti", "UTC +03:00"],
  ["DM", "Dominica", "America/Dominica", "UTC -04:00"],
  ["DO", "Dominican Republic", "America/Santo_Domingo", "UTC -04:00"],
  ["EC", "Ecuador", "America/Guayaquil", "UTC -05:00"],
  ["EC", "Ecuador", "Pacific/Galapagos", "UTC -06:00"],
  ["EG", "Egypt", "Africa/Cairo", "UTC +02:00"],
  ["SV", "El Salvador", "America/El_Salvador", "UTC -06:00"],
  ["GQ", "Equatorial Guinea", "Africa/Malabo", "UTC +01:00"],
  ["ER", "Eritrea", "Africa/Asmara", "UTC +03:00"],
  ["EE", "Estonia", "Europe/Tallinn", "UTC +03:00"],
  ["ET", "Ethiopia", "Africa/Addis_Ababa", "UTC +03:00"],
  ["FK", "Falkland Islands (Malvinas)", "Atlantic/Stanley", "UTC -03:00"],
  ["FO", "Faroe Islands", "Atlantic/Faroe", "UTC +01:00"],
  ["FJ", "Fiji", "Pacific/Fiji", "UTC +12:00"],
  ["FI", "Finland", "Europe/Helsinki", "UTC +03:00"],
  ["FR", "France", "Europe/Paris", "UTC +02:00"],
  ["GF", "French Guiana", "America/Cayenne", "UTC -03:00"],
  ["PF", "French Polynesia", "Pacific/Gambier", "UTC -09:00"],
  ["PF", "French Polynesia", "Pacific/Marquesas", "UTC -09:30"],
  ["PF", "French Polynesia", "Pacific/Tahiti", "UTC -10:00"],
  ["TF", "French Southern Territories", "Indian/Kerguelen", "UTC +05:00"],
  ["GA", "Gabon", "Africa/Libreville", "UTC +01:00"],
  ["GM", "Gambia", "Africa/Banjul", "UTC"],
  ["GE", "Georgia", "Asia/Tbilisi", "UTC +04:00"],
  ["DE", "Germany", "Europe/Berlin", "UTC +02:00"],
  ["DE", "Germany", "Europe/Busingen", "UTC +02:00"],
  ["GH", "Ghana", "Africa/Accra", "UTC"],
  ["GI", "Gibraltar", "Europe/Gibraltar", "UTC +02:00"],
  ["GR", "Greece", "Europe/Athens", "UTC +03:00"],
  ["GL", "Greenland", "America/Danmarkshavn", "UTC"],
  ["GL", "Greenland", "America/Godthab", "UTC -02:00"],
  ["GL", "Greenland", "America/Scoresbysund", "UTC"],
  ["GL", "Greenland", "America/Thule", "UTC -03:00"],
  ["GD", "Grenada", "America/Grenada", "UTC -04:00"],
  ["GP", "Guadeloupe", "America/Guadeloupe", "UTC -04:00"],
  ["GU", "Guam", "Pacific/Guam", "UTC +10:00"],
  ["GT", "Guatemala", "America/Guatemala", "UTC -06:00"],
  ["GG", "Guernsey", "Europe/Guernsey", "UTC +01:00"],
  ["GN", "Guinea", "Africa/Conakry", "UTC"],
  ["GW", "Guinea-Bissau", "Africa/Bissau", "UTC"],
  ["GY", "Guyana", "America/Guyana", "UTC -04:00"],
  ["HT", "Haiti", "America/Port-au-Prince", "UTC -04:00"],
  ["VA", "Holy See (Vatican City State)", "Europe/Vatican", "UTC +02:00"],
  ["HN", "Honduras", "America/Tegucigalpa", "UTC -06:00"],
  ["HK", "Hong Kong", "Asia/Hong_Kong", "UTC +08:00"],
  ["HU", "Hungary", "Europe/Budapest", "UTC +02:00"],
  ["IS", "Iceland", "Atlantic/Reykjavik", "UTC"],
  ["IN", "India", "Asia/Kolkata", "UTC +05:30"],
  ["ID", "Indonesia", "Asia/Jakarta", "UTC +07:00"],
  ["ID", "Indonesia", "Asia/Jayapura", "UTC +09:00"],
  ["ID", "Indonesia", "Asia/Makassar", "UTC +08:00"],
  ["ID", "Indonesia", "Asia/Pontianak", "UTC +07:00"],
  ["IR", "Iran, Islamic Republic of", "Asia/Tehran", "UTC +04:30"],
  ["IQ", "Iraq", "Asia/Baghdad", "UTC +03:00"],
  ["IE", "Ireland", "Europe/Dublin", "UTC +01:00"],
  ["IM", "Isle of Man", "Europe/Isle_of_Man", "UTC +01:00"],
  ["IL", "Israel", "Asia/Jerusalem", "UTC +03:00"],
  ["IT", "Italy", "Europe/Rome", "UTC +02:00"],
  ["JM", "Jamaica", "America/Jamaica", "UTC -05:00"],
  ["JP", "Japan", "Asia/Tokyo", "UTC +09:00"],
  ["JE", "Jersey", "Europe/Jersey", "UTC +01:00"],
  ["JO", "Jordan", "Asia/Amman", "UTC +03:00"],
  ["KZ", "Kazakhstan", "Asia/Almaty", "UTC +06:00"],
  ["KZ", "Kazakhstan", "Asia/Aqtau", "UTC +05:00"],
  ["KZ", "Kazakhstan", "Asia/Aqtobe", "UTC +05:00"],
  ["KZ", "Kazakhstan", "Asia/Atyrau", "UTC +05:00"],
  ["KZ", "Kazakhstan", "Asia/Oral", "UTC +05:00"],
  ["KZ", "Kazakhstan", "Asia/Qostanay", "UTC +06:00"],
  ["KZ", "Kazakhstan", "Asia/Qyzylorda", "UTC +05:00"],
  ["KE", "Kenya", "Africa/Nairobi", "UTC +03:00"],
  ["KI", "Kiribati", "Pacific/Enderbury", "UTC +13:00"],
  ["KI", "Kiribati", "Pacific/Kiritimati", "UTC +14:00"],
  ["KI", "Kiribati", "Pacific/Tarawa", "UTC +12:00"],
  [
    "KP",
    "Korea, Democratic People's Republic of",
    "Asia/Pyongyang",
    "UTC +09:00",
  ],
  ["KR", "Korea, Republic of", "Asia/Seoul", "UTC +09:00"],
  ["KW", "Kuwait", "Asia/Kuwait", "UTC +03:00"],
  ["KG", "Kyrgyzstan", "Asia/Bishkek", "UTC +06:00"],
  ["LA", "Lao People's Democratic Republic", "Asia/Vientiane", "UTC +07:00"],
  ["LV", "Latvia", "Europe/Riga", "UTC +03:00"],
  ["LB", "Lebanon", "Asia/Beirut", "UTC +03:00"],
  ["LS", "Lesotho", "Africa/Maseru", "UTC +02:00"],
  ["LR", "Liberia", "Africa/Monrovia", "UTC"],
  ["LY", "Libya", "Africa/Tripoli", "UTC +02:00"],
  ["LI", "Liechtenstein", "Europe/Vaduz", "UTC +02:00"],
  ["LT", "Lithuania", "Europe/Vilnius", "UTC +03:00"],
  ["LU", "Luxembourg", "Europe/Luxembourg", "UTC +02:00"],
  ["MO", "Macao", "Asia/Macau", "UTC +08:00"],
  [
    "MK",
    "Macedonia, the Former Yugoslav Republic of",
    "Europe/Skopje",
    "UTC +02:00",
  ],
  ["MG", "Madagascar", "Indian/Antananarivo", "UTC +03:00"],
  ["MW", "Malawi", "Africa/Blantyre", "UTC +02:00"],
  ["MY", "Malaysia", "Asia/Kuala_Lumpur", "UTC +08:00"],
  ["MY", "Malaysia", "Asia/Kuching", "UTC +08:00"],
  ["MV", "Maldives", "Indian/Maldives", "UTC +05:00"],
  ["ML", "Mali", "Africa/Bamako", "UTC"],
  ["MT", "Malta", "Europe/Malta", "UTC +02:00"],
  ["MH", "Marshall Islands", "Pacific/Kwajalein", "UTC +12:00"],
  ["MH", "Marshall Islands", "Pacific/Majuro", "UTC +12:00"],
  ["MQ", "Martinique", "America/Martinique", "UTC -04:00"],
  ["MR", "Mauritania", "Africa/Nouakchott", "UTC"],
  ["MU", "Mauritius", "Indian/Mauritius", "UTC +04:00"],
  ["YT", "Mayotte", "Indian/Mayotte", "UTC +03:00"],
  ["MX", "Mexico", "America/Bahia_Banderas", "UTC -05:00"],
  ["MX", "Mexico", "America/Cancun", "UTC -05:00"],
  ["MX", "Mexico", "America/Chihuahua", "UTC -06:00"],
  ["MX", "Mexico", "America/Hermosillo", "UTC -07:00"],
  ["MX", "Mexico", "America/Matamoros", "UTC -05:00"],
  ["MX", "Mexico", "America/Mazatlan", "UTC -06:00"],
  ["MX", "Mexico", "America/Merida", "UTC -05:00"],
  ["MX", "Mexico", "America/Mexico_City", "UTC -05:00"],
  ["MX", "Mexico", "America/Monterrey", "UTC -05:00"],
  ["MX", "Mexico", "America/Ojinaga", "UTC -06:00"],
  ["MX", "Mexico", "America/Tijuana", "UTC -07:00"],
  ["FM", "Micronesia, Federated States of", "Pacific/Chuuk", "UTC +10:00"],
  ["FM", "Micronesia, Federated States of", "Pacific/Kosrae", "UTC +11:00"],
  ["FM", "Micronesia, Federated States of", "Pacific/Pohnpei", "UTC +11:00"],
  ["MD", "Moldova, Republic of", "Europe/Chisinau", "UTC +03:00"],
  ["MC", "Monaco", "Europe/Monaco", "UTC +02:00"],
  ["MN", "Mongolia", "Asia/Choibalsan", "UTC +08:00"],
  ["MN", "Mongolia", "Asia/Hovd", "UTC +07:00"],
  ["MN", "Mongolia", "Asia/Ulaanbaatar", "UTC +08:00"],
  ["ME", "Montenegro", "Europe/Podgorica", "UTC +02:00"],
  ["MS", "Montserrat", "America/Montserrat", "UTC -04:00"],
  ["MA", "Morocco", "Africa/Casablanca", "UTC +01:00"],
  ["MZ", "Mozambique", "Africa/Maputo", "UTC +02:00"],
  ["MM", "Myanmar", "Asia/Yangon", "UTC +06:30"],
  ["NA", "Namibia", "Africa/Windhoek", "UTC +02:00"],
  ["NR", "Nauru", "Pacific/Nauru", "UTC +12:00"],
  ["NP", "Nepal", "Asia/Kathmandu", "UTC +05:45"],
  ["NL", "Netherlands", "Europe/Amsterdam", "UTC +02:00"],
  ["NC", "New Caledonia", "Pacific/Noumea", "UTC +11:00"],
  ["NZ", "New Zealand", "Pacific/Auckland", "UTC +12:00"],
  ["NZ", "New Zealand", "Pacific/Chatham", "UTC +12:45"],
  ["NI", "Nicaragua", "America/Managua", "UTC -06:00"],
  ["NE", "Niger", "Africa/Niamey", "UTC +01:00"],
  ["NG", "Nigeria", "Africa/Lagos", "UTC +01:00"],
  ["NU", "Niue", "Pacific/Niue", "UTC -11:00"],
  ["NF", "Norfolk Island", "Pacific/Norfolk", "UTC +11:00"],
  ["MP", "Northern Mariana Islands", "Pacific/Saipan", "UTC +10:00"],
  ["NO", "Norway", "Europe/Oslo", "UTC +02:00"],
  ["OM", "Oman", "Asia/Muscat", "UTC +04:00"],
  ["PK", "Pakistan", "Asia/Karachi", "UTC +05:00"],
  ["PW", "Palau", "Pacific/Palau", "UTC +09:00"],
  ["PS", "Palestine, State of", "Asia/Gaza", "UTC +03:00"],
  ["PS", "Palestine, State of", "Asia/Hebron", "UTC +03:00"],
  ["PA", "Panama", "America/Panama", "UTC -05:00"],
  ["PG", "Papua New Guinea", "Pacific/Bougainville", "UTC +11:00"],
  ["PG", "Papua New Guinea", "Pacific/Port_Moresby", "UTC +10:00"],
  ["PY", "Paraguay", "America/Asuncion", "UTC -04:00"],
  ["PE", "Peru", "America/Lima", "UTC -05:00"],
  ["PH", "Philippines", "Asia/Manila", "UTC +08:00"],
  ["PN", "Pitcairn", "Pacific/Pitcairn", "UTC -08:00"],
  ["PL", "Poland", "Europe/Warsaw", "UTC +02:00"],
  ["PT", "Portugal", "Atlantic/Azores", "UTC"],
  ["PT", "Portugal", "Atlantic/Madeira", "UTC +01:00"],
  ["PT", "Portugal", "Europe/Lisbon", "UTC +01:00"],
  ["PR", "Puerto Rico", "America/Puerto_Rico", "UTC -04:00"],
  ["QA", "Qatar", "Asia/Qatar", "UTC +03:00"],
  ["RO", "Romania", "Europe/Bucharest", "UTC +03:00"],
  ["RU", "Russian Federation", "Asia/Anadyr", "UTC +12:00"],
  ["RU", "Russian Federation", "Asia/Barnaul", "UTC +07:00"],
  ["RU", "Russian Federation", "Asia/Chita", "UTC +09:00"],
  ["RU", "Russian Federation", "Asia/Irkutsk", "UTC +08:00"],
  ["RU", "Russian Federation", "Asia/Kamchatka", "UTC +12:00"],
  ["RU", "Russian Federation", "Asia/Khandyga", "UTC +09:00"],
  ["RU", "Russian Federation", "Asia/Krasnoyarsk", "UTC +07:00"],
  ["RU", "Russian Federation", "Asia/Magadan", "UTC +11:00"],
  ["RU", "Russian Federation", "Asia/Novokuznetsk", "UTC +07:00"],
  ["RU", "Russian Federation", "Asia/Novosibirsk", "UTC +07:00"],
  ["RU", "Russian Federation", "Asia/Omsk", "UTC +06:00"],
  ["RU", "Russian Federation", "Asia/Sakhalin", "UTC +11:00"],
  ["RU", "Russian Federation", "Asia/Srednekolymsk", "UTC +11:00"],
  ["RU", "Russian Federation", "Asia/Tomsk", "UTC +07:00"],
  ["RU", "Russian Federation", "Asia/Ust-Nera", "UTC +10:00"],
  ["RU", "Russian Federation", "Asia/Vladivostok", "UTC +10:00"],
  ["RU", "Russian Federation", "Asia/Yakutsk", "UTC +09:00"],
  ["RU", "Russian Federation", "Asia/Yekaterinburg", "UTC +05:00"],
  ["RU", "Russian Federation", "Europe/Astrakhan", "UTC +04:00"],
  ["RU", "Russian Federation", "Europe/Kaliningrad", "UTC +02:00"],
  ["RU", "Russian Federation", "Europe/Kirov", "UTC +03:00"],
  ["RU", "Russian Federation", "Europe/Moscow", "UTC +03:00"],
  ["RU", "Russian Federation", "Europe/Samara", "UTC +04:00"],
  ["RU", "Russian Federation", "Europe/Saratov", "UTC +04:00"],
  ["RU", "Russian Federation", "Europe/Ulyanovsk", "UTC +04:00"],
  ["RU", "Russian Federation", "Europe/Volgograd", "UTC +04:00"],
  ["RW", "Rwanda", "Africa/Kigali", "UTC +02:00"],
  ["RE", "Réunion", "Indian/Reunion", "UTC +04:00"],
  ["BL", "Saint Barthélemy", "America/St_Barthelemy", "UTC -04:00"],
  [
    "SH",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Atlantic/St_Helena",
    "UTC",
  ],
  ["KN", "Saint Kitts and Nevis", "America/St_Kitts", "UTC -04:00"],
  ["LC", "Saint Lucia", "America/St_Lucia", "UTC -04:00"],
  ["MF", "Saint Martin (French part)", "America/Marigot", "UTC -04:00"],
  ["PM", "Saint Pierre and Miquelon", "America/Miquelon", "UTC -02:00"],
  [
    "VC",
    "Saint Vincent and the Grenadines",
    "America/St_Vincent",
    "UTC -04:00",
  ],
  ["WS", "Samoa", "Pacific/Apia", "UTC +13:00"],
  ["SM", "San Marino", "Europe/San_Marino", "UTC +02:00"],
  ["ST", "Sao Tome and Principe", "Africa/Sao_Tome", "UTC"],
  ["SA", "Saudi Arabia", "Asia/Riyadh", "UTC +03:00"],
  ["SN", "Senegal", "Africa/Dakar", "UTC"],
  ["RS", "Serbia", "Europe/Belgrade", "UTC +02:00"],
  ["SC", "Seychelles", "Indian/Mahe", "UTC +04:00"],
  ["SL", "Sierra Leone", "Africa/Freetown", "UTC"],
  ["SG", "Singapore", "Asia/Singapore", "UTC +08:00"],
  ["SX", "Sint Maarten (Dutch part)", "America/Lower_Princes", "UTC -04:00"],
  ["SK", "Slovakia", "Europe/Bratislava", "UTC +02:00"],
  ["SI", "Slovenia", "Europe/Ljubljana", "UTC +02:00"],
  ["SB", "Solomon Islands", "Pacific/Guadalcanal", "UTC +11:00"],
  ["SO", "Somalia", "Africa/Mogadishu", "UTC +03:00"],
  ["ZA", "South Africa", "Africa/Johannesburg", "UTC +02:00"],
  [
    "GS",
    "South Georgia and the South Sandwich Islands",
    "Atlantic/South_Georgia",
    "UTC -02:00",
  ],
  ["SS", "South Sudan", "Africa/Juba", "UTC +03:00"],
  ["ES", "Spain", "Africa/Ceuta", "UTC +02:00"],
  ["ES", "Spain", "Atlantic/Canary", "UTC +01:00"],
  ["ES", "Spain", "Europe/Madrid", "UTC +02:00"],
  ["LK", "Sri Lanka", "Asia/Colombo", "UTC +05:30"],
  ["SD", "Sudan", "Africa/Khartoum", "UTC +02:00"],
  ["SR", "Suriname", "America/Paramaribo", "UTC -03:00"],
  ["SJ", "Svalbard and Jan Mayen", "Arctic/Longyearbyen", "UTC +02:00"],
  ["SZ", "Swaziland", "Africa/Mbabane", "UTC +02:00"],
  ["SE", "Sweden", "Europe/Stockholm", "UTC +02:00"],
  ["CH", "Switzerland", "Europe/Zurich", "UTC +02:00"],
  ["SY", "Syrian Arab Republic", "Asia/Damascus", "UTC +03:00"],
  ["TW", "Taiwan, Province of China", "Asia/Taipei", "UTC +08:00"],
  ["TJ", "Tajikistan", "Asia/Dushanbe", "UTC +05:00"],
  ["TZ", "Tanzania, United Republic of", "Africa/Dar_es_Salaam", "UTC +03:00"],
  ["TH", "Thailand", "Asia/Bangkok", "UTC +07:00"],
  ["TL", "Timor-Leste", "Asia/Dili", "UTC +09:00"],
  ["TG", "Togo", "Africa/Lome", "UTC"],
  ["TK", "Tokelau", "Pacific/Fakaofo", "UTC +13:00"],
  ["TO", "Tonga", "Pacific/Tongatapu", "UTC +13:00"],
  ["TT", "Trinidad and Tobago", "America/Port_of_Spain", "UTC -04:00"],
  ["TN", "Tunisia", "Africa/Tunis", "UTC +01:00"],
  ["TR", "Turkey", "Europe/Istanbul", "UTC +03:00"],
  ["TM", "Turkmenistan", "Asia/Ashgabat", "UTC +05:00"],
  ["TC", "Turks and Caicos Islands", "America/Grand_Turk", "UTC -04:00"],
  ["TV", "Tuvalu", "Pacific/Funafuti", "UTC +12:00"],
  ["UG", "Uganda", "Africa/Kampala", "UTC +03:00"],
  ["UA", "Ukraine", "Europe/Kiev", "UTC +03:00"],
  ["UA", "Ukraine", "Europe/Simferopol", "UTC +03:00"],
  ["UA", "Ukraine", "Europe/Uzhgorod", "UTC +03:00"],
  ["UA", "Ukraine", "Europe/Zaporozhye", "UTC +03:00"],
  ["AE", "United Arab Emirates", "Asia/Dubai", "UTC +04:00"],
  ["GB", "United Kingdom", "Europe/London", "UTC +01:00"],
  ["US", "United States", "America/Adak", "UTC -09:00"],
  ["US", "United States", "America/Anchorage", "UTC -08:00"],
  ["US", "United States", "America/Boise", "UTC -06:00"],
  ["US", "United States", "America/Chicago", "UTC -05:00"],
  ["US", "United States", "America/Denver", "UTC -06:00"],
  ["US", "United States", "America/Detroit", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Indianapolis", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Knox", "UTC -05:00"],
  ["US", "United States", "America/Indiana/Marengo", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Petersburg", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Tell_City", "UTC -05:00"],
  ["US", "United States", "America/Indiana/Vevay", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Vincennes", "UTC -04:00"],
  ["US", "United States", "America/Indiana/Winamac", "UTC -04:00"],
  ["US", "United States", "America/Juneau", "UTC -08:00"],
  ["US", "United States", "America/Kentucky/Louisville", "UTC -04:00"],
  ["US", "United States", "America/Kentucky/Monticello", "UTC -04:00"],
  ["US", "United States", "America/Los_Angeles", "UTC -07:00"],
  ["US", "United States", "America/Menominee", "UTC -05:00"],
  ["US", "United States", "America/Metlakatla", "UTC -08:00"],
  ["US", "United States", "America/New_York", "UTC -04:00"],
  ["US", "United States", "America/Nome", "UTC -08:00"],
  ["US", "United States", "America/North_Dakota/Beulah", "UTC -05:00"],
  ["US", "United States", "America/North_Dakota/Center", "UTC -05:00"],
  ["US", "United States", "America/North_Dakota/New_Salem", "UTC -05:00"],
  ["US", "United States", "America/Phoenix", "UTC -07:00"],
  ["US", "United States", "America/Sitka", "UTC -08:00"],
  ["US", "United States", "America/Yakutat", "UTC -08:00"],
  ["US", "United States", "Pacific/Honolulu", "UTC -10:00"],
  [
    "UM",
    "United States Minor Outlying Islands",
    "Pacific/Midway",
    "UTC -11:00",
  ],
  ["UM", "United States Minor Outlying Islands", "Pacific/Wake", "UTC +12:00"],
  ["UY", "Uruguay", "America/Montevideo", "UTC -03:00"],
  ["UZ", "Uzbekistan", "Asia/Samarkand", "UTC +05:00"],
  ["UZ", "Uzbekistan", "Asia/Tashkent", "UTC +05:00"],
  ["VU", "Vanuatu", "Pacific/Efate", "UTC +11:00"],
  ["VE", "Venezuela, Bolivarian Republic of", "America/Caracas", "UTC -04:00"],
  ["VN", "Viet Nam", "Asia/Ho_Chi_Minh", "UTC +07:00"],
  ["VG", "Virgin Islands, British", "America/Tortola", "UTC -04:00"],
  ["VI", "Virgin Islands, U.S.", "America/St_Thomas", "UTC -04:00"],
  ["WF", "Wallis and Futuna", "Pacific/Wallis", "UTC +12:00"],
  ["EH", "Western Sahara", "Africa/El_Aaiun", "UTC +01:00"],
  ["YE", "Yemen", "Asia/Aden", "UTC +03:00"],
  ["ZM", "Zambia", "Africa/Lusaka", "UTC +02:00"],
  ["ZW", "Zimbabwe", "Africa/Harare", "UTC +02:00"],
  ["AX", "Åland Islands", "Europe/Mariehamn", "UTC +03:00"],
];

const url = [
  {
    region: "Asia",
    apiUrl: "https://api.sg.healthbeats.co/v1",
    gothumb: "https://gothumb.sg.healthbeats.co",
    loginUrl: "https://login.sg.healthbeats.co",
  },
  {
    region: "Africa",
    apiUrl: "https://api.sg.healthbeats.co/v1",
    gothumb: "https://gothumb.sg.healthbeats.co",
    loginUrl: "https://login.sg.healthbeats.co",
  },
  {
    region: "America",
    apiUrl: "https://api.us.healthbeats.co/v1",
    gothumb: "https://gothumb.us.healthbeats.co",
    loginUrl: "https://login.us.healthbeats.co",
  },
  {
    region: "Australia",
    apiUrl: "https://api.au.healthbeats.co/v1",
    gothumb: "https://gothumb.au.healthbeats.co",
    loginUrl: "https://login.au.healthbeats.co",
  },
  {
    region: "Oceania",
    apiUrl: "https://api.au.healthbeats.co/v1",
    gothumb: "https://gothumb.au.healthbeats.co",
    loginUrl: "https://login.au.healthbeats.co",
  },
  {
    region: "Pacific",
    apiUrl: "https://api.au.healthbeats.co/v1",
    gothumb: "https://gothumb.au.healthbeats.co",
    loginUrl: "https://login.au.healthbeats.co",
  },
];
module.exports = { countries, timezonedb, url };
